# Generated by Django 5.2.4 on 2025-09-01 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0003_camiseta_activa_camiseta_fecha_creacion_and_more'),
        ('mi_primer_app', '0003_datos_iniciales'),
    ]

    operations = [
    ]
